services:
  app:
    build: .
    container_name: tripare-app
    ports:
      - "3000:3000"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - temporal
      - redis

  worker:
    build: .
    container_name: tripare-worker
    command: node dist/worker.js
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      SUPPLIER_A_URL: http://app:3000/supplierA/hotels
      SUPPLIER_B_URL: http://app:3000/supplierB/hotels
    depends_on:
      temporal:
        condition: service_started
      app:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: tripare-redis

  postgres:
    image: postgres:15-alpine
    container_name: tripare-postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    volumes:
      - temporal-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 5s
      timeout: 5s
      retries: 10

  temporal:
    image: temporalio/auto-setup:latest
    container_name: tripare-temporal
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  temporal-postgres-data: